spring:
  datasource:
    #配置多個DataSource
#    primary (先改成 djohnmall 看是否命名能成功使用到資料庫)
    djohnmall:
      type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/djohnmall?serverTimezone=Asia/Taipei&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    #    second (先改成 second 看是否命名能成功使用到資料庫)
    mallsecurity:
      type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/mallsecurity?serverTimezone=Asia/Taipei&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver